version: 2
updates:

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    labels:
      - "dependencies"
      - "skip changeset"
      - "actions"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        update-types:
        - "patch"

  # NPM
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "skip changeset"
      - "npm"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
        - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
        - "patch"

  - package-ecosystem: "npm"
    directory: "/demo"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "skip changeset"
      - "npm"
    groups:
      all-demo:
        update-types:
        - "patch"


  # Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "skip changeset"
      - "bundler"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
        - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
        - "patch"
  - package-ecosystem: "bundler"
    directory: "/demo"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "skip changeset"
      - "bundler"
    groups:
      all-demo:
        update-types:
        - "patch"