name: Docs Build

on:
  push:
    branches-ignore:
      - main


jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-docs-${{ hashFiles('**/Gemfile.lock') }}
      - name: Generate docs and statuses
        run: |
          gem install bundler:2.2.9
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake docs:build
          bundle exec rake statuses:dump
      - name: Commit & Push Docs Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add -f docs static/statuses.json static/arguments.yml static/classes.yml
          git commit -m "docs: build docs" || true
          git push
      - name: Set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run docs
        run: |
          cd docs
          yarn
          yarn develop & npx wait-on http://localhost:8000
      - name: Run axe for examples for changed components
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:8000/components/autocompleteitem --exit