name: Lint

on:
  pull_request:
    branches:
      - '*'

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get specific changed files
      id: changed-files
      uses: tj-actions/changed-files@v41.1.1
      with:
        files: |
          docs/**/*.md
          .github/**/*.md
          README.md
          CONTRIBUTING.md
          CODE_OF_CONDUCT.md
    - uses: xt0rted/markdownlint-problem-matcher@v2
      if: steps.changed-files.outputs.any_changed == 'true'
    - uses: actions/setup-node@v4
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        node-version: 16
        cache: 'npm'
    - name: Lint with Markdownlint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        npm ci
        npx markdownlint-cli2 ${{ steps.changed-files.outputs.all_changed_files }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get specific changed files
      id: changed-files
      uses: tj-actions/changed-files@v41.1.1
      with:
        files: |
          app/**/*.rb
          lib/**/*.rb
          demo/**/*.rb
          test/**/*.rb
    - uses: ruby/setup-ruby@v1
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - name: Lint with Rubocop
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        bundle exec rubocop ${{ steps.changed-files.outputs.all_changed_files }} --format github

  erblint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41.1.1
      with:
        files: |
          app/components/**/*.erb
    - uses: ruby/setup-ruby@v1
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - name: Lint with ERB Lint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        bundle exec erblint ${{ steps.changed-files.outputs.all_changed_files }} --format github

  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41.1.1
      with:
        files: |
          app/components/**/*.ts
    - uses: actions/setup-node@v4
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        node-version: 16
        cache: 'npm'
    - name: Lint with ESLint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        npm ci
        npx eslint --quiet ${{ steps.changed-files.outputs.all_changed_files }}

  stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41.1.1
      with:
        files: |
          app/components/**/*.pcss
          lib/postcss_mixins/*.pcss
    - uses: actions/setup-node@v4
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        node-version: 16
        cache: 'npm'
    - name: Lint with Stylelint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        npm ci
        npx stylelint ${{ steps.changed-files.outputs.all_changed_files }} -f "github"
