name: Lint

on:
  pull_request:
    branches:
      - '*'
  merge_group:
    branches:
      - main
    types:
      - checks_requested
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get specific changed files
      id: changed-files
      uses: tj-actions/changed-files@8cba46e29c11878d930bca7870bb54394d3e8b21
      with:
        files: |
          docs/**/*.md
          .github/**/*.md
          README.md
          CONTRIBUTING.md
          CODE_OF_CONDUCT.md
    - uses: xt0rted/markdownlint-problem-matcher@v3
      if: steps.changed-files.outputs.any_changed == 'true'
    - uses: actions/setup-node@v5
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        cache: 'npm'
    - name: Lint with Markdownlint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        npm ci
        npx markdownlint-cli2 ${{ steps.changed-files.outputs.all_changed_files }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get specific changed files
      id: changed-files
      uses: tj-actions/changed-files@8cba46e29c11878d930bca7870bb54394d3e8b21
      with:
        files: |
          app/**/*.rb
          lib/**/*.rb
          demo/**/*.rb
          test/**/*.rb
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Lint with Rubocop
      run: script/rubocop --format github

  erblint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@8cba46e29c11878d930bca7870bb54394d3e8b21
      with:
        files: |
          app/components/**/*.erb
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Lint with ERB Lint
      run: script/erblint --format github

  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@8cba46e29c11878d930bca7870bb54394d3e8b21
      with:
        files: |
          app/components/**/*.ts
    - uses: actions/setup-node@v5
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        cache: 'npm'
    - name: Lint with ESLint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        npm ci
        npx eslint --quiet ${{ steps.changed-files.outputs.all_changed_files }}

  stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@8cba46e29c11878d930bca7870bb54394d3e8b21
      with:
        files: |
          app/components/**/*.pcss
          lib/postcss_mixins/*.pcss
    - uses: actions/setup-node@v5
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        cache: 'npm'
    - name: Lint with Stylelint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        npm ci
        npx stylelint --rd -q ${{ steps.changed-files.outputs.all_changed_files }} --custom-formatter=stylelint-actions-formatters

  herb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Lint with Herb
      run: |
        npx @herb-tools/linter
